name: jnigen_example_kotlin
description: a simple dart package using jnigen with Kotlin
version: 1.0.0
repository: https://github.com/mahdikhashan/jnigen_example_kotlin

environment:
  sdk: ^3.5.4

dependencies:
  jni: ^0.12.2
  path: ^1.8.0

dev_dependencies:
  jnigen: ^0.12.2
  lints: ^5.1.0
  test: ^1.24.0
