// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as _$core;

import 'package:jni/_internal.dart' as _$jni;
import 'package:jni/jni.dart' as _$jni;

final _ExampleKtClass =
    _$jni.JClass.forName(r'com/github/dart_lang/jnigen/ExampleKt');

final _id_sum = _ExampleKtClass.staticMethodId(
  r'sum',
  r'(II)I',
);

final _sum = _$jni.ProtectedJniExtensions.lookup<
            _$jni.NativeFunction<
                _$jni.JniResult Function(
                    _$jni.Pointer<_$jni.Void>,
                    _$jni.JMethodIDPtr,
                    _$jni.VarArgs<(_$jni.Int32, _$jni.Int32)>)>>(
        'globalEnv_CallStaticIntMethod')
    .asFunction<
        _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

/// from: `static public final int sum(int i, int i1)`
int sum(
  int i,
  int i1,
) {
  return _sum(_ExampleKtClass.reference.pointer, _id_sum as _$jni.JMethodIDPtr,
          i, i1)
      .integer;
}
